name: Demo to test CI on calculator

on:  
  push:
    branches:
      - master
  schedule:
    - cron: '30 14 * * MON-FRI'
jobs:
  build:
    runs-on:  windows-latest
    steps:
      - name: Checkout to repsitory
        uses:  actions/checkout@v3

      - name: Download and setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
        continue-on-error: true
      - name: Download and setup maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version:  3.6.3
      - name: Build using maven
        run: mvn clean install
  test:
      needs: build
      runs-on: ${{  needs.build.outputs.runs-on }}
      steps:
        - name:  Run-Test
          run:  mvn test -D"cucumber.filter.tags=@ui"
          env: 
            Display:  :19
            CUCUMBER_PUBLISH_TOKEN:  d63d365a-79c0-4dd8-b216-2277ba15d362
            continue-on-error:  true
        
        - uses:  actions/upload-artifact@v3
          if: always()
          with:
              name: Report
              path: test-output
              retention-days:  30
            
     
